### ISSUE TITLE
ags types

### ISSUE THREAD

**Issue by ArtemChandragupta** [webdev03/nixos#1]
Hi! I am a NixOS user, also ags user. Now I am trying to migrate to agsv2 and seen your config.

I meet [this](https://github.com/Aylur/ags/issues/617) problem. Installing `gobject-introspection` does not help me.

I have similar ags setup as yours  (home manager + config folder), to generate types I try to run `ags types ~/nix/home-modules/ags/config  -d --tsconfig`

Have you meet this problem? Have you solved it?

**Comment by imdevarsh** [comment]
Hi @ArtemChandragupta !
I didn't face this problem when migrating to AGS v2.
Maybe the packages in https://github.com/webdev03/nixos/blob/8bc1d2ee5af5959b2481cc8ffac5cc8bf7d93c83/homeManagerModules/desktop/hyprland.nix#L149 fixed it? I have no idea
Good luck!
- @webdev03

**Comment by ArtemChandragupta** [comment]
Is your lsp complains that it can't find type declarations and that it can't find the name 'React'?
![image](https://github.com/user-attachments/assets/cb16ef76-234f-490a-8f98-0c5ee3c70283)

![image](https://github.com/user-attachments/assets/46bbc31d-89b2-46fe-b845-c51fb16322c3)

**Comment by imdevarsh** [comment]
I use VSCodium and that issue doesn't happen for me after I have compiled the types. There will be an `@girs` folder.

**Comment by ArtemChandragupta** [comment]
Oh, i got it. I just need to launch project from the root folder (where ts config lives). Not convenient, but works.

Thank you for attention!
